Create skeleton for photo gallery
runtimerevolution/revent-app pull request #13
Opened 2022-09-01 09:46 UTC by andrevieira11

2022-09-02 08:22 UTC, hugo-serra requested changes

2022-09-02 08:22 UTC, hugo-serra commented on pages/index.js
> +const API = "http://127.0.0.1:8000/photo/";
put this in an env file

2022-09-06 22:06 UTC, hugo-serra requested changes

2022-09-06 22:06 UTC, hugo-serra commented on pages/contest/[id].js
> +    body.append("user", "5d2ee9f3-7f36-4861-ad59-4297aa96f932");
Add a TODO here to refactor when we have auth

2022-09-06 22:06 UTC, hugo-serra commented on pages/contest/[id].js
> +function BlurImage({ contestId, submissionId, url, user, description }) {
This seems like a Component, let's create a components folder and place all the components inside

2022-09-06 22:06 UTC, hugo-serra commented on pages/index.js
> +async function getSubmissionList() {
This should be in a service

2022-09-06 22:06 UTC, hugo-serra commented on pages/index.js
> +async function getUserList() {
This should be in a service

2022-09-06 22:06 UTC, hugo-serra commented on pages/index.js
> +  async function uploadToServer() {
This should be in a service with a better name

2022-09-06 22:06 UTC, hugo-serra commented on services/utils.js
> +const NEXT_PUBLIC_GET = process.env.NEXT_PUBLIC_GET;
Get and post dont need to be environment variables. We can use class constants here

2022-09-06 22:06 UTC, hugo-serra commented on services/utils.js
> +const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;
This file is a service for what? It should be named after that.

2022-09-07 13:04 UTC, hugo-serra approved these changes

2022-09-07 13:04 UTC, hugo-serra commented on pages/contest/[id].js
> +  let submissions;
this should probably have a default value

2022-09-07 13:04 UTC, hugo-serra commented on pages/contest/[id].js
> +  let submissions;
as well as the others

2022-09-07 14:10 UTC, JoaoCVerissimo approved these changes

2022-09-07 14:12 UTC, merged