Create layout component
runtimerevolution/revent-app pull request #22
Opened 2022-09-06 19:55 UTC by andrevieira11

2022-09-06 22:20 UTC, hugo-serra requested changes
https://nextjs.org/docs/basic-features/layouts

2022-09-06 22:20 UTC, hugo-serra commented on pages/contest/[id].js
> +import Layout from "../../services/Layout.js";
This is a single layout for all pages, move to app

2022-09-06 22:20 UTC, hugo-serra commented on services/Layout.js
> +import Head from "next/head";
This is a component, not a service

2022-09-07 14:12 UTC, JoaoCVerissimo approved these changes

2022-09-08 09:53 UTC, hugo-serra approved these changes

2022-09-08 10:56 UTC, merged