Contest Pinterest like layout
runtimerevolution/revent-app pull request #55
Opened 2023-05-16 16:48 UTC by miguelrodrigues22

Changed Contest gallery layout to be more like pinterest.

2023-05-26 10:37 UTC, JoaoCVerissimo approved these changes

2023-05-26 10:37 UTC, JoaoCVerissimo commented on components/Contest.tsx
> +        <h3 className='text-gray-900 font-medium text-lg mb-2'>
Instead of using mb-2 to create a gap i believe. You can also use in the div gap-2 or space to create the gap you want between elements inside.

2023-05-26 10:37 UTC, JoaoCVerissimo commented on components/Contest.tsx
> +        <p className='text-gray-600 text-sm'>{contest.date_end}</p>
date_end should be mapped before usage. dateEnd would be a better fit.

2023-05-26 10:37 UTC, JoaoCVerissimo commented on components/Contest.tsx
> +      key={index}
Contest id is better than using index for key mappings. It will avoid re-rendering previous contests if the request runs again.

2023-05-26 10:37 UTC, JoaoCVerissimo commented on pages/index.tsx
> +              <Contest contest={contest} index={index} />
Contest.id in index if possible

2023-05-29 23:14 UTC, JdFSilva requested changes

2023-05-29 23:14 UTC, JdFSilva commented on services/reventService.tsx
>    const contests = [
each contest should have an id

2023-05-29 23:14 UTC, JdFSilva commented on pages/index.tsx
> +              <Contest contest={contest} index={contest.id} />
you can just pass the contest and get the contest id inside the `Contest` component

2023-05-29 23:14 UTC, JdFSilva commented on components/helpers/interfaces.tsx
>  export interface HomeProps {
can we move the components props into the components files?

2023-05-29 23:14 UTC, JdFSilva commented on components/helpers/interfaces.tsx
>  export interface HomeProps {
this file should only be used for types or interfaces that are used in multiple places or that don't make sense to be in a specific file

2023-05-29 23:14 UTC, JdFSilva commented on components/helpers/interfaces.tsx
>  export interface ContestType {
interface called `ContestType`? shouldn't it just be `Contest`?

2023-05-29 23:14 UTC, JdFSilva commented on components/Contest.tsx
>  }
you don't need this, you already have the `ContestType` interface on the helpers, it's the same interface

2023-05-29 23:14 UTC, JdFSilva commented on components/Contest.tsx
>    index: number
don't need index, contest already has an id

2023-05-29 23:14 UTC, JdFSilva commented on components/Contest.tsx
> +export default function Contest({ contest, index }: ContestProps) {
don't need index

2023-05-29 23:14 UTC, JdFSilva commented on components/Contest.tsx
> +      key={index}
this should just be `key={contest.id}`

2023-05-30 11:29 UTC, JdFSilva commented on pages/index.tsx
> +}
this interface is used in multiple places so it should be on the helpers

2023-05-30 11:46 UTC, JdFSilva approved these changes

2023-05-30 13:10 UTC, merged