Create User menu
runtimerevolution/revent-app pull request #57
Opened 2023-05-29 10:28 UTC by miguelrodrigues22

Create User Menu with

- View Profile
- My Photos
- Settings
- Sign Out

Create empty pages for

- View Profile
- Settings

Create My Photos page like the Collections page

2023-05-29 10:43 UTC, tiagocardoso98 approved these changes

2023-06-07 09:41 UTC, JdFSilva commented on components/helpers/interfaces.tsx
> +  picture: Picture[]
should this be named `pictures` instead?

2023-06-07 09:41 UTC, JdFSilva commented on components/helpers/interfaces.tsx
> +export interface MyPhoto {
should this be named `MyPhotos` instead?

2023-06-07 09:41 UTC, JdFSilva commented on components/helpers/interfaces.tsx
>  export interface ContestFilterProps {
keep the props on the component files

2023-06-07 09:41 UTC, JdFSilva commented on components/Navbar/Navbar.tsx
> +            )}
this should be on it's own component

2023-06-07 09:41 UTC, JdFSilva commented on pages/myphotos/index.tsx
> +export default function MyPhotos({ myphotosList }: MyPhotosProps) {
move the props into this file

2023-06-07 13:39 UTC, miguelrodrigues22 commented on components/MyPhoto.tsx
> +          <div className='font-bold text-xl mb-2'>{myphoto.name}</div>
it had in my static service yes, will change it to description

2023-06-07 14:17 UTC, JdFSilva requested changes

2023-06-07 14:17 UTC, JdFSilva commented on components/Navbar/NavigationMenu.tsx
> +export default function NavigationMenu({ setShowUserMenu }: setShowUserMenu) {
can we rename `NavigationMenu` to `UserMenu`?

2023-06-07 14:17 UTC, JdFSilva commented on components/Navbar/NavigationMenu.tsx
> +interface setShowUserMenu {
name of the props should be `NameOfTheComponentProps`

2023-06-07 14:17 UTC, JdFSilva commented on components/Navbar/Navbar.tsx
> +              <NavigationMenu setShowUserMenu={setShowUserMenu} />
UserMenu?

2023-06-07 14:19 UTC, miguelrodrigues22 commented on components/Navbar/Navbar.tsx
> +              <NavigationMenu setShowUserMenu={setShowUserMenu} />
what about it?

2023-06-07 15:08 UTC, JdFSilva approved these changes

2023-06-07 15:12 UTC, merged